debug visualize_facial_landmarks function 'jaw'
Code 'cv2.line(overlay, ptA, ptB, colors[i], 2)'
IndexError: list index out of range

because of color[7].
List color have only 7 object